global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'jhipster'

scrape_configs:
  - job_name: 'jhipster'

    scrape_interval: 5s

    metrics_path: /management/prometheus
    static_configs:
      - targets:
          - app:8080
        labels:
          instance: app:8080
          application: str_OY_kak
